### ISSUE TITLE
Review ICA to allow more than 2 components and output remixed components

### ISSUE THREAD

**Issue by wbaccinelli** [resurfemg-org/ReSurfEMG#155]
We want to have a variable number of input lead to the ICA, and the number of output shall match the number of inputs.
The algorithm should be reviewed to separate the components, identify the ECG, put it to 0 and remix the signals

**Comment by drcandacemakedamoore** [comment]
This will be written as a  two new functions seperate from the one we have (compute_ICA_two_comp_multi(emg_samples)), because in practical terms if components match the leads in, then we will have the ECG + n components . The n components then could be remixed to still give two output signals asa final step, but unclear which was requested. The functions will go into a notebook for team review.

**Comment by drcandacemakedamoore** [comment]
some work on on existing pull request # 158 (results not satisfactory but task done), needs to be put into function into main library

**Comment by ReSurfEMG** [comment]
pr #180

**Comment by drcandacemakedamoore** [comment]
This passed it's test until the morning of December 30th, under investigation... hiccup past, and incidentally formated the zeroing one better
