### ISSUE TITLE
helper_functions.show_my_power_spectrum 

### ISSUE THREAD

**Issue by drcandacemakedamoore** [resurfemg-org/ReSurfEMG#4]
Needs robust testing and analysis

**Comment by wbaccinelli** [comment]
The value computed in [this function](https://github.com/ReSurfEMG/ReSurfEMG/blob/fdb9447cefe5682d27b8cd6461cab80621d3180b/resurfemg/helper_functions.py#L326) is just the FFT, but the Power Spectrum should be the squared value of the FFT. 
While the the absolute value of FFT is plotted, the raw value is returned. Is this just to visualize the positive frequencies?

I am a bit unsure whether we should provide the power spectrum or the power spectrum density. Given the stochastic nature of the signal, maybe the PSD is more appropriate.

**Comment by wbaccinelli** [comment]
## Analysis of the current implementation

The current implementation of the helper_functions.show_my_power_spectrum function has been tested. A report is reported [here](https://github.com/ReSurfEMG/ReSurfEMG/files/9166446/analysis_spectrum_function.pdf). 

The results show that the function overall behaves as expected. Nonetheless, the following refinement has to be implemented:
- Adaptation of the visualization
- The spectrum values has to be computed as the square of the absolute value of the fft (Currently only the absolute value is computed).
- The spectrum values have to be returned, instead of the fft values
