### ISSUE TITLE
write compute_ICA_n_components

### ISSUE THREAD

**Issue by ReSurfEMG** [resurfemg-org/ReSurfEMG#86]
We need to make a version of hf.compute_ICA_two_components into a function that will take n components (other labs have 5 and 19 lead arrays to deal with)

**Comment by drcandacemakedamoore** [comment]
compute_ICA_two_comp_multi in helper functions is this versions. it lacks testing, but please let's review and discuss first

**Comment by drcandacemakedamoore** [comment]
We now also have on where you select your components to check at multi_lead_type.compute_ICA_two_comp_selective()

**Comment by wbaccinelli** [comment]
I have a couple of comments:
- Do we need to have two different functions? The more general one (compute_ICA_two_comp_selective) works in all the scenarios and the additional arguments are not mandatory, given the default values.
- [Here](https://github.com/ReSurfEMG/ReSurfEMG/blob/39b8e5124ec3d678a239a60ea0074e83608a371e/resurfemg/multi_lead_type.py#L51) I think it is better if the function returns an error and stops, otherwise it will proceed and run into an exception.
- The descriptions mention that at least e arrays are needed, but with 2 (ECG + 1 respiratory) it should work, right?

**Comment by drcandacemakedamoore** [comment]
Technically yes, you only need two leads, I guess, so I'll change that in the doc-string. You are right, we probably don't absolutely need two functions,  but then we will need to change the pipeline so you pick which leads as parameters in the pipeline as well. So let's just keep this until I finish retro-fitting the pipeline, then probably get rid of it. Good point about making an error, I'll change the function then put it back to review again.

**Comment by drcandacemakedamoore** [comment]
@wbaccinelli rewritten to throw error on multi_lead_type.py
